version: '3.3'
services:
  env-dev-d8:
    depends_on:
      - database
    build: 
      context: .
      args:
        PHP_VERSION: 7.0
        DRUSH_VERSION: 8.1.10
        NODE_VERSION: 6.10.0
        DEVELOPER: ${USER}
    environment:
      DRUPAL_VERSION_MAYOR: 8
      MYSQL_HOST: database
      MYSQL_ROOT_PASSWORD: root
      DRUPAL_PROJECT: testd8  
      DEVELOPER: ${USER}
    container_name: env-dev-d8  
    ports:
      - 80:80
      - 8080:8080
      - 222:22
    networks:
      - back  
    volumes:
      - ./src:/home/${USER}/Proyectos
  database:
    image: mariadb
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306
    networks:
      - back   
  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 7000:80  
    networks:
      - back      
networks:
  back:
volumes:
  database_data: